name: Deploy React App

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t textoperator.

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}

      - name: Push image
        run: |
          docker tag textoperator ${{ secrets.DOCKER_USER }}/textoperator:latest
          docker push ${{ secrets.DOCKER_USER }}/textoperator:latest

